service: todo-application-backend
provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x

functions:
  tasks:
    handler: handler.app
    events:
      - http:
          method: get
          path: tasks
          cors: true
      - http:
          method: post
          path: tasks
          cors: true